FROM node:lts-alpine as build-stage
WORKDIR /homepage


COPY . .
RUN npm install --no-optional --global npm
RUN npm install vue --save --legacy-peer-deps
RUN npm install -g @vue/cli
RUN npm run build


FROM nginx:stable-alpine as production-stage

RUN ls -a
RUN rm /etc/nginx/conf.d/default.conf
COPY ./homepage.conf /etc/nginx/conf.d/homepage.conf
COPY --from=build-stage ./homepage/dist /usr/share/nginx/html/homepage
RUN ls -a /usr/share/nginx/html/homepage
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]


